package net.modjam5.makercommunity.common.world.structure;

import static net.minecraft.inventory.EntityEquipmentSlot.HEAD;

import java.util.Collections;
import java.util.List;
import java.util.Random;

import javax.annotation.Nullable;

import net.minecraft.block.Block;
import net.minecraft.entity.monster.EntityZombieVillager;
import net.minecraft.init.Biomes;
import net.minecraft.init.Blocks;
import net.minecraft.init.MobEffects;
import net.minecraft.item.ItemStack;
import net.minecraft.potion.PotionEffect;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.biome.BiomeProvider;
import net.minecraft.world.gen.structure.MapGenStructure;
import net.minecraft.world.gen.structure.StructureBoundingBox;
import net.minecraft.world.gen.structure.StructureStart;
import net.minecraftforge.items.CapabilityItemHandler;
import net.minecraftforge.items.IItemHandler;
import net.modjam5.makercommunity.common.ItemRegistry;
import net.modjam5.makercommunity.common.Registry;
import net.modjam5.makercommunity.util.MapStructureHelper;

/**
 * @author Tim Biesenbeek
 */
public class BeachStructure extends MapGenStructure implements Structure {

	private static final StructureBoundingBox boundingBox = new StructureBoundingBox(new int[]{0, 0, 0, 11, 6, 11});
	private static final List<Biome> ALLOWED_BIOMES = Collections.singletonList(Biomes.BEACH);

	@Override
	protected boolean canSpawnStructureAtCoords(int chunkX, int chunkZ) {
		return canSpawnStructureAtCoords2(chunkX, chunkZ);
	}
	@Override
	public void updateWorld(World world) {
		this.world = world;
	}

	@Override
	public StructureBoundingBox getBoundingBox() {
		return boundingBox;
	}

	@Override
	public String getStructureName() {
		return "BeachHouse";
	}

	@Nullable
	@Override
	public BlockPos getNearestStructurePos(World worldIn, BlockPos pos, boolean findUnexplored) {
		this.world = worldIn;
		BiomeProvider biomeprovider = worldIn.getBiomeProvider();
		return biomeprovider.isFixedBiome() && biomeprovider.getFixedBiome() != Biomes.BEACH ? null
				: findNearestStructurePosBySpacing(worldIn, this, pos, 80, 20, 10387319, true, 100, findUnexplored);
	}

	@Override
	public boolean canSpawnStructureAtCoords2(int chunkX, int chunkZ) {
		if (Math.abs(chunkX) < 20 || Math.abs(chunkZ) < 20) {
			return false;
		}
		Random random = this.world.setRandomSeed(2304 * chunkX, 1996 * chunkZ, 905);
		boolean rand = random.nextInt(100) + 1 <= 5;
		boolean biome = this.world.getBiomeProvider().areBiomesViable(chunkX * 16 + 8, chunkZ * 16 + 8, 4,
			ALLOWED_BIOMES);
		return rand && biome;
	}

	@Override
	protected StructureStart getStructureStart(int chunkX, int chunkZ) {
		return new Start(this, chunkX, chunkZ);
	}

	@SuppressWarnings("deprecation")
	public void generate(World world, Random random, int xPos, int zPos) {
		int i = xPos + random.nextInt(15);
		int k = zPos + random.nextInt(15);

		int chunkX = i >> 4;
		int chunkZ = k >> 4;
		int height = world.getChunkFromChunkCoords(chunkX, chunkZ).getHeight(new BlockPos(i & 0xF, 0, k & 0xF));

		int j = height - 1;

		BlockPos chest = new BlockPos(i + 5, j + 2, k + 5);
		world.setBlockState(chest, Blocks.CHEST.getDefaultState(), 3);
		TileEntity te = world.getTileEntity(chest);
		if (te instanceof TileEntityChest) {
			TileEntityChest chestTE = (TileEntityChest) te;
			IItemHandler iItemHandler = chestTE.getCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, null);
			if (iItemHandler != null) {
				iItemHandler.insertItem(world.rand.nextInt(chestTE.getSizeInventory()), MapStructureHelper
						.buildMapFor(Registry.structureRegister.byClass(BoatStructure.class), world, chest),
					false);
			}
		}

		EntityZombieVillager villager = new EntityZombieVillager(world);
		villager.setItemStackToSlot(HEAD, new ItemStack(ItemRegistry.recorders[1]));
		villager.setDropChance(HEAD, 100F);
		villager.setChild(true);
		villager.enablePersistence();
		villager.setLocationAndAngles(i + 5, j + 3, k + 5, world.rand.nextFloat() * 360F, 0);
		villager.setCustomNameTag("XJ1");
		villager.setAbsorptionAmount(10);
		villager.addPotionEffect(new PotionEffect(MobEffects.SPEED, Short.MAX_VALUE/2, 1, false, true));
		villager.addPotionEffect(new PotionEffect(MobEffects.STRENGTH, Short.MAX_VALUE/2, 0, false, true));
		villager.setAlwaysRenderNameTag(false);
		world.spawnEntity(villager);
		
		
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 1), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 1), Block.getBlockById(135).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 1), Block.getBlockById(135).getStateFromMeta(6), 3);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 1), Block.getBlockById(135).getStateFromMeta(4), 3);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 1), Block.getBlockById(135).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 1), Block.getBlockById(135).getStateFromMeta(6), 3);
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 1), Block.getBlockById(135).getStateFromMeta(4), 3);
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 1), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 2), Block.getBlockById(135).getStateFromMeta(7), 3);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 2), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 2), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 2), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 2), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 2), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 2), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 2), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 2), Block.getBlockById(135).getStateFromMeta(7), 3);
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 3), Block.getBlockById(135).getStateFromMeta(4), 3);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 3), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 3), Block.getBlockById(125).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 3), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 3), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 3), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 3), Block.getBlockById(125).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 3), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 3), Block.getBlockById(135).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 4), Block.getBlockById(135).getStateFromMeta(6), 3);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 4), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 4), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 4), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 4), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 4), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 4), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 4), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 4), Block.getBlockById(135).getStateFromMeta(6), 3);
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 5), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 5), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 5), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 5), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 5), Block.getBlockById(17).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 5), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 5), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 5), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 5), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 6), Block.getBlockById(135).getStateFromMeta(7), 3);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 6), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 6), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 6), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 6), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 6), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 6), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 6), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 6), Block.getBlockById(135).getStateFromMeta(7), 3);
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 7), Block.getBlockById(135).getStateFromMeta(4), 3);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 7), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 7), Block.getBlockById(125).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 7), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 7), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 7), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 7), Block.getBlockById(125).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 7), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 7), Block.getBlockById(135).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 8), Block.getBlockById(135).getStateFromMeta(6), 3);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 8), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 8), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 8), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 8), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 8), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 8), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 8), Block.getBlockById(126).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 8), Block.getBlockById(135).getStateFromMeta(6), 3);
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 9), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 9), Block.getBlockById(135).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 9), Block.getBlockById(135).getStateFromMeta(7), 3);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 9), Block.getBlockById(135).getStateFromMeta(4), 3);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 9), Block.getBlockById(135).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 9), Block.getBlockById(135).getStateFromMeta(7), 3);
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 9), Block.getBlockById(135).getStateFromMeta(4), 3);
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 9), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 0, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 0, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 0, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 0, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 1), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 1), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 1), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 1), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 1), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 1), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 1), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 1), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 2), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 2), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 3), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 3), Block.getBlockById(42).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 3), Block.getBlockById(42).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 3), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 4), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 4), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 5), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 6), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 6), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 7), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 7), Block.getBlockById(42).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 7), Block.getBlockById(42).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 7), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 8), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 8), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 9), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 9), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 9), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 9), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 9), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 9), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 9), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 9), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 1, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 1, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 1, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 2, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 2, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 1), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 1), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 1), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 1), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 1), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 2, k + 1), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 2, k + 1), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 1), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 2), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 2, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 2, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 2), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 3), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 3), Block.getBlockById(42).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 3), Block.getBlockById(69).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 3), Block.getBlockById(69).getStateFromMeta(10), 3);
		world.setBlockState(new BlockPos(i + 7, j + 2, k + 3), Block.getBlockById(42).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 2, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 3), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 4), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 4), Block.getBlockById(69).getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 4), Block.getBlockById(75).getStateFromMeta(4), 3);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 2, k + 4), Block.getBlockById(69).getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(i + 8, j + 2, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 4), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 5), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 5), Block.getBlockById(75).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 5), Block.getBlockById(75).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 7, j + 2, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 2, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 6), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 6), Block.getBlockById(69).getStateFromMeta(4), 3);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 6), Block.getBlockById(75).getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 2, k + 6), Block.getBlockById(69).getStateFromMeta(4), 3);
		world.setBlockState(new BlockPos(i + 8, j + 2, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 6), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 7), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 7), Block.getBlockById(42).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 7), Block.getBlockById(69).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 7), Block.getBlockById(69).getStateFromMeta(10), 3);
		world.setBlockState(new BlockPos(i + 7, j + 2, k + 7), Block.getBlockById(42).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 2, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 7), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 8), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 2, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 2, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 8), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 9), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 9), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 9), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 9), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 9), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 2, k + 9), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 2, k + 9), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 9), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 2, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 2, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 2, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 3, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 3, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 3, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 1), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 1), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 1), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 1), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 3, k + 1), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 3, k + 1), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 3, k + 1), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 1), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 2), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 3, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 3, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 3, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 2), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 3), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 3), Block.getBlockById(75).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 3, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 3, k + 3), Block.getBlockById(75).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 8, j + 3, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 3), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 4), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 3, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 3, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 3, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 4), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 5), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 3, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 3, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 3, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 5), Block.getBlockById(17).getStateFromMeta(8), 3);
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 6), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 3, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 3, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 3, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 6), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 7), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 7), Block.getBlockById(75).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 3, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 3, k + 7), Block.getBlockById(75).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 8, j + 3, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 7), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 8), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 3, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 3, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 3, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 8), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 9), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 9), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 9), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 9), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 3, k + 9), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 3, k + 9), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 3, k + 9), Block.getBlockById(20).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 9), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 3, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 3, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 3, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 3, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 3, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 3, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 3, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 3, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 3, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 3, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 3, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 0), Block.getBlockById(134).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 0), Block.getBlockById(134).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 0), Block.getBlockById(134).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 0), Block.getBlockById(134).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 0), Block.getBlockById(134).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 0), Block.getBlockById(134).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 0), Block.getBlockById(134).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 0), Block.getBlockById(134).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 0), Block.getBlockById(134).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 0), Block.getBlockById(134).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 0), Block.getBlockById(134).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 1), Block.getBlockById(134).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 1), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 1), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 1), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 1), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 1), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 1), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 1), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 1), Block.getBlockById(134).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 2), Block.getBlockById(134).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 2), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 2), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 2), Block.getBlockById(134).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 3), Block.getBlockById(134).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 3), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 3), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 3), Block.getBlockById(134).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 4), Block.getBlockById(134).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 4), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 4), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 4), Block.getBlockById(134).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 5), Block.getBlockById(134).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 5), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 5), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 5), Block.getBlockById(134).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 6), Block.getBlockById(134).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 6), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 6), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 6), Block.getBlockById(134).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 7), Block.getBlockById(134).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 7), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 7), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 7), Block.getBlockById(134).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 8), Block.getBlockById(134).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 8), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 8), Block.getBlockById(17).getStateFromMeta(9), 3);
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 8), Block.getBlockById(134).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 9), Block.getBlockById(134).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 9), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 9), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 9), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 9), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 9), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 9), Block.getBlockById(17).getStateFromMeta(5), 3);
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 9), Block.getBlockById(17).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 9), Block.getBlockById(134).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 0, j + 4, k + 10), Block.getBlockById(134).getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(i + 1, j + 4, k + 10), Block.getBlockById(134).getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(i + 2, j + 4, k + 10), Block.getBlockById(134).getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(i + 3, j + 4, k + 10), Block.getBlockById(134).getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(i + 4, j + 4, k + 10), Block.getBlockById(134).getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(i + 5, j + 4, k + 10), Block.getBlockById(134).getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(i + 6, j + 4, k + 10), Block.getBlockById(134).getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(i + 7, j + 4, k + 10), Block.getBlockById(134).getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(i + 8, j + 4, k + 10), Block.getBlockById(134).getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(i + 9, j + 4, k + 10), Block.getBlockById(134).getStateFromMeta(3), 3);
		world.setBlockState(new BlockPos(i + 10, j + 4, k + 10), Block.getBlockById(134).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 0, j + 5, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 5, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 5, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 5, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 5, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 5, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 5, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 5, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 5, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 5, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 5, k + 0), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 5, k + 1), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 5, k + 1), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 2, j + 5, k + 1), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 3, j + 5, k + 1), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 4, j + 5, k + 1), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 5, j + 5, k + 1), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 6, j + 5, k + 1), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 7, j + 5, k + 1), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 8, j + 5, k + 1), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 9, j + 5, k + 1), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 10, j + 5, k + 1), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 5, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 5, k + 2), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 2, j + 5, k + 2), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 3, j + 5, k + 2), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 4, j + 5, k + 2), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 5, j + 5, k + 2), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 6, j + 5, k + 2), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 7, j + 5, k + 2), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 8, j + 5, k + 2), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 9, j + 5, k + 2), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 10, j + 5, k + 2), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 5, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 5, k + 3), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 2, j + 5, k + 3), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 3, j + 5, k + 3), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 4, j + 5, k + 3), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 5, j + 5, k + 3), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 6, j + 5, k + 3), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 7, j + 5, k + 3), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 8, j + 5, k + 3), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 9, j + 5, k + 3), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 10, j + 5, k + 3), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 5, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 5, k + 4), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 2, j + 5, k + 4), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 3, j + 5, k + 4), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 4, j + 5, k + 4), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 5, j + 5, k + 4), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 6, j + 5, k + 4), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 7, j + 5, k + 4), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 8, j + 5, k + 4), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 9, j + 5, k + 4), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 10, j + 5, k + 4), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 5, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 5, k + 5), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 2, j + 5, k + 5), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 3, j + 5, k + 5), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 4, j + 5, k + 5), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 5, j + 5, k + 5), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 6, j + 5, k + 5), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 7, j + 5, k + 5), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 8, j + 5, k + 5), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 9, j + 5, k + 5), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 10, j + 5, k + 5), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 5, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 5, k + 6), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 2, j + 5, k + 6), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 3, j + 5, k + 6), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 4, j + 5, k + 6), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 5, j + 5, k + 6), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 6, j + 5, k + 6), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 7, j + 5, k + 6), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 8, j + 5, k + 6), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 9, j + 5, k + 6), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 10, j + 5, k + 6), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 5, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 5, k + 7), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 2, j + 5, k + 7), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 3, j + 5, k + 7), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 4, j + 5, k + 7), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 5, j + 5, k + 7), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 6, j + 5, k + 7), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 7, j + 5, k + 7), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 8, j + 5, k + 7), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 9, j + 5, k + 7), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 10, j + 5, k + 7), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 5, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 5, k + 8), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 2, j + 5, k + 8), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 3, j + 5, k + 8), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 4, j + 5, k + 8), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 5, j + 5, k + 8), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 6, j + 5, k + 8), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 7, j + 5, k + 8), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 8, j + 5, k + 8), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 9, j + 5, k + 8), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 10, j + 5, k + 8), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 5, k + 9), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 5, k + 9), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 2, j + 5, k + 9), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 3, j + 5, k + 9), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 4, j + 5, k + 9), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 5, j + 5, k + 9), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 6, j + 5, k + 9), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 7, j + 5, k + 9), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 8, j + 5, k + 9), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 9, j + 5, k + 9), Block.getBlockById(126).getStateFromMeta(1), 3);
		world.setBlockState(new BlockPos(i + 10, j + 5, k + 9), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 0, j + 5, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 1, j + 5, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 2, j + 5, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 3, j + 5, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 4, j + 5, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 5, j + 5, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 6, j + 5, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 7, j + 5, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 8, j + 5, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 5, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 10, j + 5, k + 10), Block.getBlockById(0).getStateFromMeta(0), 3);
		world.setBlockState(new BlockPos(i + 9, j + 1, k + 5), Block.getBlockById(194).getStateFromMeta(2), 3);
		world.setBlockState(new BlockPos(i + 9, j + 2, k + 5), Block.getBlockById(194).getStateFromMeta(8), 3);
	}
}